- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/PetalsApplication.kt
- fastlane/metadata/android/en-US/changelogs/3002.txt
- fastlane/metadata/android/pt-BR/changelogs/3002.txt
When assuming the default value, null, as the database name, SQLDelight
implicitly assumes it's an InMemory database, and thus won't persist
data to disk.
This commit fixes that by giving a name to the database.
> 🐛 Add name to database

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/navigation/Usage.kt
- app/src/main/kotlin/br/com/colman/petals/use/AddUseButton.kt
- app/src/main/kotlin/br/com/colman/petals/use/io/UseImporter.kt
- app/src/main/kotlin/br/com/colman/petals/use/repository/UseRepository.kt
- app/src/main/sqldelight/br/com/colman/petals/Use.sq
- app/src/test/kotlin/br/com/colman/petals/use/io/UseImporterSpec.kt
- app/src/test/kotlin/br/com/colman/petals/use/repository/UseRepositoryTest.kt
After the database migration on release 3.0.0, the insert stopped behaving like an Upsert, as it used to in Objectbox.
This commit changes the insert in the database to be an Upsert, as specified in https://www.sqlite.org/lang_UPSERT.html. The changes were made to file Use.sq.
This behavior is only to the database, and thus a single test was added to UseRepositoryTest to ensure it. All other files changed are collateral of the rename refactor.
Closes #124
> 🐛 Fix edit use not working

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/PetalsApplication.kt
- fastlane/metadata/android/en-US/changelogs/3200.txt
- gradle/libs.versions.toml
With the upsert syntax, devices not supporting SQLite 3.22+ won't work with the upsert syntax.
https://stackoverflow.com/questions/2421189/version-of-sqlite-used-in-android
This reduces by a lot the number of supported devices. This commit fixes that
> Fix bug preventing some devices from inserting Use

- app/build.gradle.kts
Google forbids apps with target sdk  <= 31. This commit increments that
version in order to fix it.
Fixes #137
> Bump targetSDK to version 33

- app/build.gradle.kts
- app/src/main/sqldelight/br/com/colman/petals/Use.sq
- app/src/test/kotlin/br/com/colman/petals/use/repository/UseRepositoryTest.kt
- fastlane/metadata/android/en-US/changelogs/3204.txt
This commit changes the logic on Use.sq to only include uses in the past
as eligible for being the last use.
Fixes #131
> Fix timer misbehaving when adding uses in the future

- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerDayOfWeek.kt
As it was, dark mode rendered every text black, and it was invisible. This commit adds the coloring following what was used in UsePerHourGraph
Closes #177
> 💄 Add colors to UsePerDayOfWeek

- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
Changed the options to the following:
1.HH:mm
2.KK:mm a
3.HH:mm:ss
4.KK:mm:ss a
This closes the issue https://github.com/LeoColman/Petals/issues/267 .
Fixed the unit test accordingly.
> 🚸 Improve Time Format Options

- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/card/AverageUseCard.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseBlock.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
- app/src/main/res/values/strings.xml
Should solve #292 adding the option to select 0-3 decimal places to be displayed.
Currently settings page does not scroll #313
Also changed decimals displayed on Stats page average use card from 4 to 2 on the cost.
> Add setting to specify precision on numbers #292

- app/src/androidTest/kotlin/br/com/colman/petals/use/io/FileWriterTest.kt
- app/src/main/kotlin/br/com/colman/petals/use/io/FileWriter.kt
- gradle/libs.versions.toml
This changes the hardcoded "PetalsExport.csv" fileName to a unique one that identifies the date it was saved
Example: "PetalsExport-2023-09-25.csv"
> Add date to exported fileName

- .github/workflows/build.main.kts
- .github/workflows/dependency-license-analysis.main.kts
- .github/workflows/generate-action-bindings.main.kts
- .github/workflows/lint.main.kts
- .github/workflows/release.main.kts
- .github/workflows/unit-tests.main.kts
Contains adjustments for breaking changes, as described in https://github.com/typesafegithub/github-workflows-kt/releases/tag/v1.9.0.
> ⬆ Update github-workflows-kt monorepo to v1.10.0

- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerDayOfWeekGraph.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerHourGraph.kt
Unused imports have been removed and label generation in UsePerHourGraph
and UsePerDayOfWeekGraph has been changed. Now, instead of using a
pluralStringResource, the label method from Period is used, simplifying
the code and centralizing label generation.
Closes #521
> 💄 Refactor label generation in graph classes

- app/src/main/kotlin/br/com/colman/petals/hittimer/HitTimer.kt
- app/src/test/kotlin/br/com/colman/petals/hittimer/HitTimerTest.kt
The durationMillisecondsDisabled method in HitTimer class now includes a
conditional to prevent it from showing 0 while milliseconds are still
present. This change will ensure more accurate time display. A matching
test has been added in HitTimerTest.kt for verification.
Closes #543
> 💄 Add check to avoid 0 in durationMillisecondsDisabled

- app/src/main/kotlin/br/com/colman/petals/use/UseBlock.kt
- app/src/main/kotlin/br/com/colman/petals/use/repository/BlockRepository.kt
- app/src/test/kotlin/br/com/colman/petals/use/repository/BlockRepositoryTest.kt
Changed the default censorship for day, week, month, year and all time periods from true to false in the BlockRepository. Additionally updated the CensureIcon and BlockText Composables in UseBlock to correctly reflect their censorship states.
Closes #581
> 🐛 Updated default censorship settings

- .github/workflows/android-tests.main.kts
- .github/workflows/android-tests.yaml
- app/src/androidTest/kotlin/br/com/colman/petals/hittimer/ComposeHitTimerTest.kt
- gradle/libs.versions.toml
The commit adds tests for Android, specifically for the ComposeHitTimer feature. It also updates the version of the Kotest library for running Android tests. Furthermore, two new workflow files have been created for
GitHub Actions to handle the execution of these Android tests.
> ✅ Add Android tests and update Kotest library version

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
- app/src/playstore/kotlin/br/com/colman/petals/playstore/MainActivity.kt
- app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
Implemented a new feature that allows the user to switch between Day mode and Night mode in the app.
This feature improves user experience as they can manually select their preferred theme, irrespective of the system default setting. Special consideration was given to persist the user's choice so that their preference is saved and applied for subsequent app uses.
The Day/Night mode switch was implemented in the Settings and Main activity, making it easily accessible for users.
Tests were also written to validate the functionality and ensure the application's robustness.
This is an important update as it gives more customization control to users, therefore improving overall app usability and user satisfaction.
> ✨ Add a Day/Night switch that doesn't depend on the System Theme

- .github/workflows/build-debug.main.kts
- .github/workflows/build-release.main.kts
- .github/workflows/dependency-license-analysis.main.kts
- .github/workflows/lint.main.kts
- .github/workflows/release.main.kts
- .github/workflows/unit-tests.main.kts
This URL is likely going to be a part of the library's API when the Maven-compatible bindings server becomes stable.
Everything to make it work is already in place, so I'm migrating known clients to the new URL.
> Switch to new domain for GitHub Actions Kotlin bindings

- app/src/main/kotlin/br/com/colman/petals/use/io/UseCsvSerializer.kt
- app/src/main/kotlin/br/com/colman/petals/use/repository/Use.kt
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/br/com/colman/petals/use/io/UseCsvSerializerTest.kt
The 'id' field has been added to the UseCsvHeaders data class and the UseCsvSerializer class. This addition has also been reflected in the corresponding test file. The label for 'id' has been added to the application's string resources.
Closes #616
> 🐛 Add 'id' field to CSV Headers and Serializer

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/settings/AppLanguage.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/LanguageListItem.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
A language selection setting is added to the settings page. The `MainActivity` now extends `AppCompatActivity` to handle changing the app language. More info on this here:
https://developer.android.com/guide/topics/resources/app-languages#androidx-impl
Closes #678
> ✨ Add app language selection setting

- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/AngerTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/DecreasedAppetiteTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/DiscomfortTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/IrritabilityTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/NervousnessAnxietyTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/RestlessnessTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/SleepDifficultyTest.kt
> ✅ Improve Coverage on data maps

- app/build.gradle.kts
Kover doesn't support integration tests anyway, so keeping Composable (ie integration-test) functions under kover reports is not helpful.
This commit makes our test coverage reflect a value closer to reality for our unit tests
> ✅ Remove @Composable from Kover reports

- app/build.gradle.kts
- app/src/test/kotlin/br/com/colman/petals/statistics/graph/formatter/DayOfWeekFormatterTest.kt
- app/src/test/kotlin/br/com/colman/petals/statistics/graph/formatter/DaysSinceFirstUseFormatterTest.kt
- app/src/test/kotlin/br/com/colman/petals/use/io/input/UseImporterTest.kt
- gradle/libs.versions.toml
Replace deprecated `forAll` with `withData` to align with new
testing practices. Adjust configurations and tests accordingly
for compatibility with the updated library.
> ⬆️ Upgrade Kotest to 6.0.1
