LeoColman/Petals

- .github/dependabot.yml
> 👷 Add Dependabot

- app/src/main/kotlin/br/com/colman/petals/hittimer/HitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/StatisticsPage.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
> 🚨 Fix Detekt issues

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/HitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/WhyTenSeconds.kt
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/br/com/colman/petals/hittimer/HitTimerTest.kt
- fastlane/metadata/android/en-US/changelogs/250.txt
- fastlane/metadata/android/pt-BR/changelogs/250.txt
> Add vibration to the end of Hit Timer

- app/src/main/kotlin/br/com/colman/petals/use/AddUseForm.kt
- Gives more space for the date to fit in its box
- Improves color of Date and Time fields to visually show they're
editable
Closes #62
> 💄 Improve Add Use Dialog

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/statistics/card/AverageUseCard.kt
- fastlane/metadata/android/en-US/changelogs/271.txt
- fastlane/metadata/android/pt-BR/changelogs/271.txt
Closes #69 
Co-authored-by: Luiz Neves Porto <dev@luiz.nevesporto.com.br>
> Add use count to Statistics

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/WhyTenSeconds.kt
- app/src/main/kotlin/br/com/colman/petals/navigation/Page.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/card/AverageUseCard.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerHourGraph.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/SymptomsPage.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/discomfort/view/DiscomfortView.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/thc/view/ThcConcentrationView.kt
- fastlane/metadata/android/en-US/changelogs/280.txt
- fastlane/metadata/android/pt-BR/changelogs/280.txt
This commit leverages MaterialTheme and its integration with the system
to provide a dark theme to Petals App.
MainActivity.kt was changed to calculate if the system is set to Dark
All other files were changed to use MaterialTheme colors instead of
their default colors.
Closes #68
> ✨ Add Dark Mode following SystemDarkMode

- app/build.gradle.kts
- gradle/libs.versions.toml
Included in the bumped dependencies are:
- Detekt
- Koin
- Android compiler
- Other libraries
> ⬆️ Bump dependency versions

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/HitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/WhyTenSeconds.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/card/AverageUseCard.kt
- app/src/main/kotlin/br/com/colman/petals/use/AddUseForm.kt
- app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
- config/detekt/detekt.yml
- fastlane/metadata/android/en-US/changelogs/281.txt
- fastlane/metadata/android/pt-BR/changelogs/281.txt
> Adjust LastUseDateTimer so that text won't break line

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/use/io/UseCsvFileImporter.kt
- app/src/main/kotlin/br/com/colman/petals/use/io/UseCsvParser.kt
- app/src/main/kotlin/br/com/colman/petals/use/repository/Use.kt
- fastlane/metadata/android/en-US/changelogs/3001.txt
- fastlane/metadata/android/pt-BR/changelogs/3001.txt
Use import was considering different IDs. However, the ids don't matter
for the database, and thus shouldn't be compared.
> 🐛 Fix Use Import

- app/src/main/kotlin/br/com/colman/petals/use/AddUseButton.kt
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> 🌐 Extract alert text from add use during pause to strings.xml

- .github/workflows/dependency-license-analysis.main.kts
- .github/workflows/dependency-license-analysis.yaml
- .github/workflows/lint.main.kts
- .github/workflows/lint.yaml
- .github/workflows/release.main.kts
- .github/workflows/release.yaml
- .github/workflows/unit-tests.main.kts
- .github/workflows/unit-tests.yaml
> ⬆️ Upgrade github-workflows-kt to version 0.31.0

- app/build.gradle.kts
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-pt/strings.xml
- fastlane/metadata/android/en-US/changelogs/3202.txt
> Replace incorrectly translated % sign

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerDayOfWeek.kt
- fastlane/metadata/android/en-US/changelogs/3301.txt
> Add localization to Day of Week graph labels

- app/src/main/kotlin/br/com/colman/petals/navigation/Page.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/StatisticsPage.kt
- app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
This change resolves #67 by adding setting for date and time format.
> 🚸 Add setting for date and time format

- .github/workflows/build.main.kts
- .github/workflows/build.yaml
> 👷 Add Build APK workflow

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/withdrawal/thc/repository/ThcConcentrationRepository.kt
- fastlane/metadata/android/en-US/changelogs/3502.txt
> 🐛 Align abstinence dot with graphs line

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/HitTimer.kt
> 🐛 Fix HitTimer resetting when screen rotates

- app/build.gradle.kts
- fastlane/metadata/android/en-US/changelogs/3504.txt
- gradle/libs.versions.toml
> Upgrade Compose Compiler version

- app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
- app/src/main/res/values/strings.xml
I have added a toast message. When user wants delete "Use", an alertDialog will pop up to confirm that user really wants to delete "Use" and then if user clicks "Yes" then "Use" will be deleted and a toast message showed up.
screenshots: -
> Toast message added

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/statistics/card/AverageUseCard.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerDayOfWeek.kt
- fastlane/metadata/android/en-US/changelogs/3700.txt
> Add Total Grams to Stats Block

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
- fastlane/metadata/android/en-US/changelogs/3800.txt
- fastlane/metadata/android/en-US/full_description.txt
> ✨ Add optional PIN to unlock the app 

- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/navigation/Page.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
- app/src/main/res/values/strings.xml
- app/src/playstore/kotlin/br/com/colman/petals/playstore/MainActivity.kt
> Ability to turn off millisecond view.

- app/src/main/kotlin/br/com/colman/petals/KoinModule.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/discomfort/repository/DiscomfortRepository.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/discomfort/view/DiscomfortView.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/interpolator/DiscomfortInterpolator.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/interpolator/ThcConcentrationInterpolator.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/thc/repository/ThcConcentrationRepository.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/thc/view/ThcConcentrationView.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/discomfort/repository/DiscomfortRepositoryTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/interpolator/DiscomfortInterpolatorTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/interpolator/ThcConcentrationInterpolatorTest.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/thc/repository/ThcConcentrationRepositoryTest.kt
- gradle/libs.versions.toml
Rewrites the internals of the classes, extracting an independent interpolator for each and adding unit tests for all added classes.
Closes #311
> ♻️ Refactors ThcConcentration and Discomfort Code

- .github/workflows/release.main.kts
- .github/workflows/release.yaml
Ref: https://github.com/entrostat/git-secret-action/pull/3
Ref: https://github.com/entrostat/git-secret-action/issues/6
Closes #350
> ⬆️ Upgrade Github Workflows Entrostat to use Embedded version

- .github/workflows/build.yaml
- .github/workflows/dependency-license-analysis.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/unit-tests.yaml
Fixing the issue described in https://kotlinlang.slack.com/archives/C02UUATR7RC/p1703337896816589. The issue was likely caused by a known issue with stale cache when calling the script locally.
This change fixes CI on the main branch.
> 💚 Fix workflow YAMLs

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/statistics/component/Period.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/graph/UsePerDayOfWeekGraph.kt
- app/src/main/kotlin/br/com/colman/petals/statistics/graph/color/Colors.kt
- fastlane/metadata/android/en-US/changelogs/321003.txt
Converted the Period class from sealed to open and added a 'minusDays'
method. Made modifications in the UsePerDayOfWeekGraph class to include
an additional 'uses3' dataset and optimized the data grouping and
filtering logic to improve weekly data management.
> 💄 Refactor Period class and enhance data handling in UsePerDayOfWeekGraph

- gradle/libs.versions.toml
> Revert "⬆ Update datastore"

- app/src/main/kotlin/br/com/colman/petals/KoinModule.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseBlock.kt
- app/src/main/kotlin/br/com/colman/petals/use/repository/BlockRepository.kt
- app/src/main/res/values/strings.xml
1.Introduce 'BlockRepository' to handle block censure with enum
BlockTypes
2.Revise 'UseBlock' function by replacing title parameter with
'blockType: BlockType'
> ✨ Add feature for censuring block values

- .github/workflows/build-debug.main.kts
- .github/workflows/build-release.main.kts
- .github/workflows/dependency-license-analysis.main.kts
- .github/workflows/lint.main.kts
- .github/workflows/release.main.kts
- .github/workflows/unit-tests.main.kts
See release notes: https://github.com/typesafegithub/github-workflows-kt/releases/tag/v2.0.0
> ⬆ Update dependency io.github.typesafegithub:github-workflows-kt to v2.0.0

- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
> 🩹 Set default setting for milliseconds to 'disabled'

- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/dialog/SwitchListItem.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/ExtendDayListItem.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/HitTimerMillisecondsEnabledListItem.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/MillisecondsBarEnabledListItem.kt
- app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseBlock.kt
- app/src/playstore/kotlin/br/com/colman/petals/playstore/MainActivity.kt
- app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
update the Settings to utilize Switch-Buttons instead of the
'enabled/disabled' text dialog for a more user-friendly control.
>  ✨ Refactor Settings to show Switch-Buttons instead of dialogs

- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/ComposeHitTimer.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
- app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/dialog/SwitchListItem.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/ExtendDayListItem.kt
- app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/HitTimerMillisecondsEnabledListItem.kt
- app/src/main/kotlin/br/com/colman/petals/use/UseBlock.kt
- app/src/playstore/kotlin/br/com/colman/petals/playstore/MainActivity.kt
- app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
Add switch button for timer milliseconds bar and day extended option
> ✨ Refactor Settings to show Switch-Buttons instead of dialog

- app/build.gradle.kts
- gradle/libs.versions.toml
> ⬆️ Replace dependency Doyaaaaken kotlin-csv by new Joizo kotlin-csv

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/KoinModule.kt
- app/src/main/kotlin/br/com/colman/petals/hittimer/HitTimerRepository.kt
- app/src/test/kotlin/br/com/colman/petals/hittimer/HitTimerRepositoryTest.kt
- gradle/libs.versions.toml
Also improves dependency injection for something compatible with unit
tests (without needing a full android context)
> ✅ Add tests to HitTimerRepository

- app/src/test/kotlin/br/com/colman/petals/use/io/UseIOModulesTest.kt
- app/src/test/kotlin/br/com/colman/petals/use/io/input/UseInputModuleTest.kt
- app/src/test/kotlin/br/com/colman/petals/use/io/output/UseOutputModuleTest.kt
> ✅ Add tests to UseIOModules

- app/src/main/kotlin/br/com/colman/petals/settings/AppLanguage.kt
- app/src/main/res/values-ta/strings.xml
> 🚑️ Fix Tamil Language Symptoms Chart

- app/build.gradle.kts
- app/src/main/kotlin/br/com/colman/petals/withdrawal/data/ChartConfig.kt
- app/src/test/kotlin/br/com/colman/petals/withdrawal/data/ChartConfigTest.kt
> ✅ Improve Coverage on ChartConfig

- .github/workflows/kover.main.kts
- .github/workflows/kover.yaml
> 💚 Fix CI not publishing the Coverage Badge anymore 

- app/src/main/kotlin/br/com/colman/petals/navigation/Usage.kt
Removed unnecessary conditional check for empty usage list. This ensures
StatsBlocks, UsageFilter, and UseCards are consistently rendered.
> 🐛 Simplify usage check in UI rendering logic.

- app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
- app/src/main/kotlin/br/com/colman/petals/theme/Colors.kt
- app/src/main/kotlin/br/com/colman/petals/withdrawal/view/WithdrawalChart.kt
Color Scheme authored by @Melissa Gomes
> 💄 Rework App Colors

- app/src/main/kotlin/br/com/colman/petals/use/UseBlock.kt
Refactor number formatting to use `NumberFormat` for locale-aware representation and consistent decimal precision. Improves data presentation and ensures proper rounding per user settings.
> ✨ Enhance number formatting in UseBlock
